language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
- npm install
script:
  - npm run build
before_deploy:
  - npm run build
  - chmod +x $TRAVIS_BUILD_DIR/package_artifacts.sh
  - "$TRAVIS_BUILD_DIR/package_artifacts.sh $TRAVIS_BUILD_DIR"
deploy:
  provider: releases
  api_key: $github_token
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/artifacts/*"
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    branch: master
    tags: true