language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
- npm install
script:
  - npm run build
deploy:
  provider: releases
  api_key: $github_token
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    branch: master
    tags: true